name: Update Phillies Score

on:
  workflow_dispatch:

  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write

jobs:
  update-score:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Update score data
        run: |
          python scripts/update_score.py

      - name: Commit score data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/score.json

          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "Update Phillies score data"
            git push
          fi
